### ISSUE TITLE
org.springframework.beans.factory.BeanDefinitionStoreException

### ISSUE THREAD

**Issue by otajisan** [otajisan/zero-scala#1]
ビルド実行
```
$ sbt assembly
[info] Loading global plugins from /Users/taji/.sbt/0.13/plugins
[info] Loading project definition from /Users/taji/IdeaProjects/zero-scala/project
[info] Set current project to zero-scala (in build file:/Users/taji/IdeaProjects/zero-scala/)
[info] Including from cache: spring-boot-starter-tomcat-1.5.3.RELEASE.jar
[info] Including from cache: jackson-annotations-2.8.0.jar
[info] Including from cache: spring-expression-4.3.8.RELEASE.jar
[info] Including from cache: jackson-core-2.8.8.jar
[info] Including from cache: spring-boot-autoconfigure-1.5.3.RELEASE.jar
[info] Including from cache: spring-web-4.3.8.RELEASE.jar
[info] Including from cache: spring-boot-starter-logging-1.5.3.RELEASE.jar
[info] Including from cache: logback-classic-1.1.11.jar
[info] Including from cache: spring-webmvc-4.3.8.RELEASE.jar
[info] Including from cache: logback-core-1.1.11.jar
[info] Including from cache: tomcat-embed-core-8.5.14.jar
[info] Including from cache: jcl-over-slf4j-1.7.25.jar
[info] Including from cache: slf4j-api-1.7.25.jar
[info] Including from cache: tomcat-embed-el-8.5.14.jar
[info] Including from cache: snakeyaml-1.17.jar
[info] Including from cache: jul-to-slf4j-1.7.25.jar
[info] Including from cache: tomcat-embed-websocket-8.5.14.jar
[info] Including from cache: log4j-over-slf4j-1.7.25.jar
[info] Including from cache: thymeleaf-spring4-3.0.0.RELEASE.jar
[info] Including from cache: thymeleaf-3.0.0.RELEASE.jar
[info] Including from cache: spring-core-4.3.8.RELEASE.jar
[info] Including from cache: attoparser-2.0.0.RELEASE.jar
[info] Including from cache: hibernate-validator-5.3.5.Final.jar
[info] Including from cache: validation-api-1.1.0.Final.jar
[info] Including from cache: scala-library-2.12.3.jar
[info] Including from cache: unbescape-1.1.3.RELEASE.jar
[info] Including from cache: spring-boot-starter-web-1.5.3.RELEASE.jar
[info] Including from cache: spring-boot-starter-1.5.3.RELEASE.jar
[info] Including from cache: spring-aop-4.3.8.RELEASE.jar
[info] Including from cache: spring-context-4.3.8.RELEASE.jar
[info] Including from cache: spring-boot-1.5.3.RELEASE.jar
[info] Including from cache: jboss-logging-3.3.0.Final.jar
[info] Including from cache: spring-beans-4.3.8.RELEASE.jar
[info] Including from cache: classmate-1.3.1.jar
[info] Including from cache: jackson-databind-2.8.8.jar
[info] Checking every *.class/*.jar file's SHA-1.
[info] Merging files...
[warn] Merging 'META-INF/INDEX.LIST' with strategy 'discard'
[warn] Merging 'META-INF/MANIFEST.MF' with strategy 'discard'
[warn] Merging 'META-INF/additional-spring-configuration-metadata.json' with strategy 'first'
[warn] Merging 'META-INF/services/javax.servlet.ServletContainerInitializer' with strategy 'filterDistinctLines'
[warn] Merging 'META-INF/spring-configuration-metadata.json' with strategy 'first'
[warn] Merging 'META-INF/spring.factories' with strategy 'first'
[warn] Merging 'META-INF/spring.handlers' with strategy 'filterDistinctLines'
[warn] Merging 'META-INF/spring.provides' with strategy 'first'
[warn] Merging 'META-INF/spring.schemas' with strategy 'filterDistinctLines'
[warn] Merging 'META-INF/spring.tooling' with strategy 'first'
[warn] Merging 'META-INF/web-fragment.xml' with strategy 'first'
[warn] Strategy 'discard' was applied to 2 files
[warn] Strategy 'filterDistinctLines' was applied to 3 files
[warn] Strategy 'first' was applied to 6 files
[info] Assembly up to date: /Users/taji/IdeaProjects/zero-scala/target/scala-2.12/zero-scala-assembly-0.1.jar
[success] Total time: 2 s, completed 2017/08/25 15:50:06
```
アプリケーション実行
```
$ java -jar target/scala-2.12/zero-scala-assembly-0.1.jar

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                  (v0.1)

2017-08-25 15:42:56.515  INFO 68989 --- [           main] scala.App                                : Starting App v0.1 on denji-no-MacBook-Air.local with PID 68989 (/Users/taji/IdeaProjects/zero-scala/target/scala-2.12/zero-scala-assembly-0.1.jar started by taji in /Users/taji/IdeaProjects/zero-scala)
2017-08-25 15:42:56.520  INFO 68989 --- [           main] scala.App                                : No active profile set, falling back to default profiles: default
2017-08-25 15:42:56.632  INFO 68989 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@29f69090: startup date [Fri Aug 25 15:42:56 JST 2017]; root of context hierarchy
2017-08-25 15:42:56.813  WARN 68989 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.zeroscala.BootConfig]; nested exception is java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
2017-08-25 15:42:56.831 ERROR 68989 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.zeroscala.BootConfig]; nested exception is java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:556) ~[zero-scala-assembly-0.1.jar:0.1]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:185) ~[zero-scala-assembly-0.1.jar:0.1]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:308) ~[zero-scala-assembly-0.1.jar:0.1]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:228) ~[zero-scala-assembly-0.1.jar:0.1]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:270) ~[zero-scala-assembly-0.1.jar:0.1]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:93) ~[zero-scala-assembly-0.1.jar:0.1]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:686) ~[zero-scala-assembly-0.1.jar:0.1]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524) ~[zero-scala-assembly-0.1.jar:0.1]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[zero-scala-assembly-0.1.jar:0.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [zero-scala-assembly-0.1.jar:0.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [zero-scala-assembly-0.1.jar:0.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [zero-scala-assembly-0.1.jar:0.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [zero-scala-assembly-0.1.jar:0.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [zero-scala-assembly-0.1.jar:0.1]
	at com.zeroscala.ZeroScala$.delayedEndpoint$com$zeroscala$ZeroScala$1(ZeroScala.scala:10) [zero-scala-assembly-0.1.jar:0.1]
	at com.zeroscala.ZeroScala$delayedInit$body.apply(ZeroScala.scala:8) [zero-scala-assembly-0.1.jar:0.1]
	at scala.Function0.apply$mcV$sp(Function0.scala:34) [zero-scala-assembly-0.1.jar:0.1]
	at scala.Function0.apply$mcV$sp$(Function0.scala:34) [zero-scala-assembly-0.1.jar:0.1]
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12) [zero-scala-assembly-0.1.jar:0.1]
	at scala.App.$anonfun$main$1$adapted(App.scala:76) [zero-scala-assembly-0.1.jar:0.1]
	at scala.App$$Lambda$5/123961122.apply(Unknown Source) [zero-scala-assembly-0.1.jar:0.1]
	at scala.collection.immutable.List.foreach(List.scala:389) [zero-scala-assembly-0.1.jar:0.1]
	at scala.App.main(App.scala:76) [zero-scala-assembly-0.1.jar:0.1]
	at scala.App.main$(App.scala:74) [zero-scala-assembly-0.1.jar:0.1]
	at com.zeroscala.ZeroScala$.main(ZeroScala.scala:8) [zero-scala-assembly-0.1.jar:0.1]
	at com.zeroscala.ZeroScala.main(ZeroScala.scala) [zero-scala-assembly-0.1.jar:0.1]
Caused by: java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
	at org.springframework.util.Assert.notEmpty(Assert.java:277) ~[zero-scala-assembly-0.1.jar:0.1]
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getCandidateConfigurations(AutoConfigurationImportSelector.java:153) ~[zero-scala-assembly-0.1.jar:0.1]
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.selectImports(AutoConfigurationImportSelector.java:95) ~[zero-scala-assembly-0.1.jar:0.1]
	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:547) ~[zero-scala-assembly-0.1.jar:0.1]
	... 25 common frames omitted
```
ここのエラーが未解決
```
2017-08-25 15:42:56.632  INFO 68989 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@29f69090: startup date [Fri Aug 25 15:42:56 JST 2017]; root of context hierarchy
2017-08-25 15:42:56.813  WARN 68989 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.zeroscala.BootConfig]; nested exception is java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
2017-08-25 15:42:56.831 ERROR 68989 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.zeroscala.BootConfig]; nested exception is java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:556) ~[zero-scala-assembly-0.1.jar:0.1]
```

**Comment by otajisan** [comment]
sbtのマイナーバージョンを下げたらうまくいった
```
//scalaVersion := "2.12.3"
scalaVersion := "2.12.2"
```
